//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DABongDa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUTHU
    {
        public string MaCT { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> SoAo { get; set; }
        public string ChieuCao { get; set; }
        public string CanNang { get; set; }
        public string ViTri { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string MaDB { get; set; }
        public Nullable<int> SoBanThang { get; set; }
        public Nullable<System.DateTime> ThoiGianRaSan { get; set; }
        public Nullable<int> SoTranThamGia { get; set; }
        public string TieuSu { get; set; }
    
        public virtual DOIBONG DOIBONG { get; set; }
    }
}
