//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DABongDa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOIBONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOIBONG()
        {
            this.CAUTHU = new HashSet<CAUTHU>();
            this.LICHTD = new HashSet<LICHTD>();
            this.LICHTD1 = new HashSet<LICHTD>();
        }
    
        public string MaDB { get; set; }
        public string TenDB { get; set; }
        public string TenHLV { get; set; }
        public string DiaChi { get; set; }
        public string TieuSu { get; set; }
        public Nullable<int> SoCauThu { get; set; }
        public Nullable<int> MaSVD { get; set; }
    
        public virtual BANGTONGKET BANGTONGKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAUTHU> CAUTHU { get; set; }
        public virtual SANVANDONG SANVANDONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHTD> LICHTD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHTD> LICHTD1 { get; set; }
    }
}
