//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DABongDa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHTD
    {
        public string MaDB1 { get; set; }
        public string MaDB2 { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public Nullable<int> MaSVD { get; set; }
        public string TenTrongTai { get; set; }
        public string GiamSatTrongTai { get; set; }
        public Nullable<System.DateTime> NgayThiDau { get; set; }
        public Nullable<int> TySo { get; set; }
        public string Kenh { get; set; }
        public Nullable<int> SoLuongKG { get; set; }
        public string SuCo { get; set; }
    
        public virtual DOIBONG DOIBONG { get; set; }
        public virtual DOIBONG DOIBONG1 { get; set; }

        internal static object ToList()
        {
            throw new NotImplementedException();
        }
    }
}
