//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DABongDa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_bongdaEntities2 : DbContext
    {
        public QL_bongdaEntities2()
            : base("name=QL_bongdaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANGTONGKET> BANGTONGKET { get; set; }
        public virtual DbSet<CAUTHU> CAUTHU { get; set; }
        public virtual DbSet<DOIBONG> DOIBONG { get; set; }
        public virtual DbSet<LICHTD> LICHTD { get; set; }
        public virtual DbSet<SANVANDONG> SANVANDONG { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
